- name: Install packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - "openjdk-8-jdk"
      - "python3"

- name: "Get files - Hadoop verion 3.3.0"
  unarchive:
    src: "{{mirror_uri_ftp}}"
    dest: "{{hadoop_base}}"
    owner: "{{user_name}}"
    group: "{{user_name}}"
    remote_src: yes
